name = "basecred"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[env.testnet]
name = "basecred-testnet"

[env.testnet.vars]
NEXTAUTH_URL = "https://basecred-testnet.nachdakwale.workers.dev"
NEXT_PUBLIC_CHAIN_ID = "84532"
NEXT_PUBLIC_CONTRACT_ADDRESS = "0x7608558Bf63f0924eC3FB5D27BD32E1440681eFE"
NEXT_PUBLIC_EXPLORER_URL = "https://sepolia.basescan.org"
NEXT_PUBLIC_NETWORK_NAME = "Base Sepolia Testnet"
NEXT_PUBLIC_RPC_URL = "https://sepolia.base.org"
NEXT_PUBLIC_TOKEN_ADDRESS = "0xD71915f25FB8b725Cb8562ad306dBF42173FF583"
NEXT_PUBLIC_DIVIDENDS_ADDRESS = "0x26621770BDC77E88BBE1bff43c84605Cd3E4feDb"
NEXT_PUBLIC_GOVERNOR_ADDRESS = "0x2d87731f8c855F11214a3873d098F383C77Ae84D"
NEXT_PUBLIC_SALE_ADDRESS = "0x3d6d4B29634967e7B6f0c149aF4eb6D63d9B8A82"

# ADMIN_PASSWORD = ""  # Do NOT set here. Use: wrangler secret put ADMIN_PASSWORD --env testnet

[[env.testnet.ratelimits]]
name = "API_RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 8, period = 60 }

[env.mainnet]
name = "basecred-mainnet"

[env.mainnet.vars]
NEXTAUTH_URL = "https://basecred-mainnet.nachdakwale.workers.dev"
NEXT_PUBLIC_CHAIN_ID = "8453"
NEXT_PUBLIC_CONTRACT_ADDRESS = "0x0000000000000000000000000000000000000000"
NEXT_PUBLIC_EXPLORER_URL = "https://basescan.org"
NEXT_PUBLIC_NETWORK_NAME = "Base Mainnet"
NEXT_PUBLIC_RPC_URL = "https://browser-rpc-provider.example.invalid"

# ADMIN_PASSWORD = ""  # Do NOT set here. Use: wrangler secret put ADMIN_PASSWORD --env mainnet

[[env.mainnet.ratelimits]]
name = "API_RATE_LIMITER"
namespace_id = "2001"
simple = { limit = 5, period = 60 }
